version: "3.7"

services:
  node-service:
    build: .
    ports:
      - 3000:3000
    container_name: node-service
    restart: unless-stopped
  
  db-service:
    image: postgres:12.2
    hostname: postgres
    ports:
      - 5432:5432
    volumes:
      - db-storage-volume:/var/lib/postgresql/data
    environment:
      - "POSTGRES_PASSWORD=${DB_PASSWORD}"

  adminer:
    image: adminer:4.7
    ports:
      - 8080:8080


volumes:
    db-storage-volume:
